version: 2

sources:
  - name: seeds_customers
    tables:
      - name: stg_customers

  - name: seeds_products
    tables:
      - name: stg_products

  - name: seeds_sales
    tables:
      - name: stg_sales